### ISSUE TITLE
How to provide an implementation for an interface or at least mock it?

### ISSUE THREAD

**Issue by longnguyen2306** [j-easy/easy-random#352]
Hi,

for testing purpose, I used you guys' library to generate quick random bean. However, there is a problem with a class, which has an interface as an attribute. This interface doesn't do anything in the test and will not be needed. Is there any way to provide an implementation for this interface or at least mock this interface to avoid the exception:

`Caused by: org.jeasy.random.ObjectCreationException: Unable to create a random instance of type interface com.example.ExampleInterface`

thanks,

**Comment by PascalSchumacher** [comment]
Hi,

try enabling classpath-scanning, see: https://github.com/j-easy/easy-random/wiki/Randomization-parameters#classpath-scanning

**Comment by longnguyen2306** [comment]
Problem solved with:

```
EasyRandomParameters parameters = new EasyRandomParameters()
            .randomize(InterfaceExample.class, InterfaceExampleImpl::new)
```
