### ISSUE TITLE
Custom bean validation [Feature request]

### ISSUE THREAD

**Issue by terryBaz** [j-easy/easy-random#378]
Is it possible for `easy-random-bean-validation` to randomize based on my custom validations and **not the ones provided by**  `javax.validation.constraints`.

**Comment by benas** [comment]
@terryBaz Can you give an example please?

**Comment by benas** [comment]
I'm closing this for now as I believe there is no feature to implement here. A custom randomizer is the way to go as shown in my previous comment.

Feel free to add a comment here if necessary.
