### ISSUE TITLE
Populating subtype of typed map

### ISSUE THREAD

**Issue by kenfehling** [j-easy/easy-random#380]
Version: 4.1.0

Hi, thanks for this library! I think I've found a bug; I've written a failing unit test for it and tried to track down the problem.

```
@Data
class MapSubtype extends HashMap<String, Object> { }

@Data
class Item extends MapSubtype {
    private String name;
}

@Data
class Container extends MapSubtype {
    private Item item;
}

@Test
public void membersOfMapSubtypesMightBePopulated() {
    EasyRandomParameters parameters = new EasyRandomParameters();
    EasyRandom easyRandom = new EasyRandom(parameters);
    final Container container = easyRandom.nextObject(Container.class);
    assertThat(container.item.name).isNotNull();
}
```

I believe it has to do with `isMapType` and `isParameterizedType` not checking at the same levels of the inheritance hierarchy: `isMapType` means "Is this type a map or is there any map type ancestor?" but `isParameterizedType` means just "Is this type parameterized?" So there can be a situation where there's a map supertype which is parameterized, so `isMapType` returns `true` but `isParameterizedType` returns `false`, so it isn't populated.

**Comment by benas** [comment]
Hi @kenfehling ,

Thank you for reporting this issue! I do confirm, ER fails to randomize the type in this case. We had a similar case with enums in #242, but its applicable to any custom type that extends a generic type. Here is another example with a collection:

```java
@Data
class MyCustomListType extends ArrayList<String> { }

@Data
class Person {
    private String name;
    private MyCustomListType addresses;
}

@Test
public void test() {
    final Person person = new EasyRandom().nextObject(Person.class);
    assertThat(person.name).isNotNull();
    assertThat(person.addresses).isNotEmpty();
}
```

This test fails. However, it passes if you change the type of `addresses` from `MyCustomListType` to `ArrayList<String>`. So your analysis is correct: `isMapType`/`isCollectionType` could be out of sync with `isParameterizedType` with this tricky type hierarchy. 

I [already tried](https://github.com/j-easy/easy-random/issues/242#issuecomment-441480572) to fix this issue by saving the generic type from the root object in the randomization context and propagate it down the tree.. but in the end, I gave up against type erasure and decided to wait for reified generics. 

As you might have seen, there is a section about type erasure in the [know limitations](https://github.com/j-easy/easy-random/wiki/known-limitations#type-erasure) page, and I think the use case presented here is one of the edge cases where ER fails. So I added a reference to this issue in the aforementioned section.

You can use a custom randomizer for your type. Thanks again for raising the issue and providing a failing test!
