### ISSUE TITLE
The same sequences of data are repeated in context of different randomizers

### ISSUE THREAD

**Issue by mjureczko** [j-easy/easy-random#404]
Actual:
AbstractRandomizer creates a new instance of Random. Random is consistently initialised with the same seed, hence different instances of Random repeats the same sequences of data. I prepared a test that manifests the issue with regard to generating longs and objects containing a field of type long:
https://github.com/mjureczko/easy-random/commit/09ccd032359475e2b2d6847c1cbdd600282b7454
In the test I got exactly the same numbers from subsequent calls of nextLong() and nextObject(ClassWithLong.class) which cannot be considered random.

Expected:
nextObject(ClassWithLong.class) should not repeat the values generated by nextLong()

**Comment by benas** [comment]
@mjureczko looks the same as #403 which you closed, can we close this as well?

**Comment by mjureczko** [comment]
I closed #403, because I made a mistake in the test that was included there and I didn't want to keep an incorrectly reported issue open. Nonetheless, the randomness is not as random as one may expect, so this issue cannot be closed. The description of #404 is the same as #403, I only changed the test that manifests the malfunction.

**Comment by benas** [comment]
ok thanks, I will take a look.

**Comment by mjureczko** [comment]
I'm going to submit a merge request with a fix, but I'm not ready with it yet.

**Comment by benas** [comment]
I don't see this as an issue. As explained in #406, the suggested approach breaks the design of `EasyRandom`.

You can use a custom randomizer for `ClassWithLong` and you will get different sequences of numbers. Here is a quick example based on your test (which makes it pass):

```java
@Test
void sequencesOfDataShouldNotBeReusedBetweenRandomizers() {
    //given
    class ClassWithLong {
        long number;
    }
    Set<Long> longs = new HashSet<>();
    Set<Long> objects = new HashSet<>();
    EasyRandom easyRandom = new EasyRandom(new EasyRandomParameters().randomize(ClassWithLong.class, () -> {
        ClassWithLong classWithLong = new ClassWithLong();
        classWithLong.number = new LongRandomizer().getRandomValue();
        return classWithLong;
    }));
    int N = 10;

    //when
    for (int i = 0; i < N; i++) {
        long nextLong = easyRandom.nextLong();
        longs.add(nextLong);
        long nextObject = easyRandom.nextObject(ClassWithLong.class).number;
        objects.add(nextObject);
    }

    //then
    objects.addAll(longs);
    assertThat(objects).hasSize(2 * N);
}
```

Thank you for opening this issue anyway!

**Comment by mjureczko** [comment]
Hi @benas, indeed the issue can be easily overcome when you know what is going one. Nonetheless, I believed that it is worth of an issue as it is an unexpected breaking change with regard to random-beans. I had a number of failing tests due to this issue when moving on to easy-random. Moreover, I find the behaviour counterintuitive. Consider the following scenario:
1. Create an entity with long id, i.e. nextObject(EntityWithLongId.class)
2. Query the database using some random id, i.e. findById(nextLong())
3. Out of the blue, query returned entity created in step 1.
Long can have so many different values, that one does not expect to have it repeated so quickly. Furthermore, the user needs to be aware of the implementation details to know when the repetition will happen.
