### ISSUE TITLE
Parametrization of nested objects generation

### ISSUE THREAD

**Issue by mjureczko** [j-easy/easy-random#405]
The behaviour regarding nested objects was described in details in https://github.com/j-easy/easy-random/issues/384. While I do not have doubts that it works as designed, I see the benefits of having the possibility to force it to work differently. I see here two scenarios:

1. Assume there is a nested object that guards its collections (fields) against null values by initializing them (e.g. in the constructor) with empty collections. As a consequence, it is not possible to have there null field unless reflection is used. However, EasyRandom uses reflection, and when reaching 'randomizationDepth' lefts the fields uninitialized. When using such objects in tests, we face NullPointerException in places where production code will never have them.
**Solution**: it would be convenient to have the possibility to chose to no to use objects with uninitialized fields and instead on the 'randomizationDepth' -1 level have empty collections.

2. When the 'objectPoolSize' is close to the number of nested objects, there is a considerable possibility of having infinity recursion, e.g. object A can have list containing among others the object A itself. This is something the production code may prevent by executing some logic, but since EasyRandom uses reflection, can easily overcome such invariants. When using such objects in tests, we may face the infinity recursion.
**Solution**:  it would be convenient to have the possibility to avoid reusing objects that are already used on the path leading to the root object, at least as long as there are in the pool objects that fulfil the condition.

**Comment by benas** [comment]
> While I do not have doubts that it works as designed, I see the benefits of having the possibility to force it to work differently

Easy Random cannot cover all cases. If you want to make it work differently, you can use custom randomizers for such recursive types or provide a custom `ObjectFactory` implementation that is smart enough to covers those cases.

I'm closing this issue as explained in #412 . Thank you.
