### ISSUE TITLE
How to generate complicated object with List<String> and Map<String,String>

### ISSUE THREAD

**Issue by KaimingWan** [j-easy/easy-random#407]
I reference the wiki, but I can't find the way to generate a custom object with List<String> or Map<String,String>

**Comment by benas** [comment]
> I can't find the way to generate a custom object with List or Map<String,String>

here is an example:

```java
@Test
void testIssue407() {
    class Person {
        List<String> names;
        Map<String, String> emails;
    }

    EasyRandom easyRandom = new EasyRandom();
    Person person = easyRandom.nextObject(Person.class);
    Assertions.assertThat(person.names).isNotEmpty();
    Assertions.assertThat(person.emails).isNotEmpty();
}
```

This test passes and generates `List<String>` and `Map<String, String>` as expected:

![Screenshot 2020-04-11 at 23 50 35](https://user-images.githubusercontent.com/1210553/79055714-75de8780-7c4f-11ea-8349-e66f1042a555.png)

However, complex nested generic types are deliberately not supported as mentioned in the [wiki](https://github.com/j-easy/easy-random/wiki/known-limitations#composite-collections).
