### ISSUE TITLE
Feature > Allow to customize randomizer registry regsitered to solve performance issues

### ISSUE THREAD

**Issue by ghilainm** [j-easy/easy-random#410]
I am experimenting a very slow generation since I added easy-random-bean-validation to the classpath.

I would like the possibility to easily customize the BeanValidationAnnotationHandler registered to limit to the one which I know are performant.

**Edit**: this is the Size annotation handling which is super slow! More precisely, it is the map/collections part which is slow, the string part seems to be ok.

**Comment by benas** [comment]
What if we try to fix the performance issue instead? Can you share the type you are trying to randomize and some numbers about what you consider slow regarding the `Size` annotation?

**Comment by benas** [comment]
> I would like the possibility to easily customize the BeanValidationAnnotationHandler registered to limit to the one which I know are performant.

It is possible to exclude/replace annotations handlers by using a custom registry. Here is a quick example:

```java
import javax.validation.constraints.Size;

import org.jeasy.random.EasyRandomParameters;
import org.jeasy.random.randomizers.misc.NullRandomizer;

public class MyCustomBeanValidationRandomizerRegistry extends BeanValidationRandomizerRegistry {

	@Override
	public void init(EasyRandomParameters parameters) {
		super.init(parameters);
		annotationHandlers.put(Size.class, field -> new NullRandomizer());
		// exclude or replace other annotation handlers if needed
	}
}
```

```java
@Test
void customRegistryTest() {
    // given
    class Person {
        @Size(min = 5, max = 10)
        private String name;
    }
    
    EasyRandomParameters parameters = new EasyRandomParameters()
            .randomizerRegistry(new MyCustomBeanValidationRandomizerRegistry());
    EasyRandom easyRandom = new EasyRandom(parameters);
    
    // when
    Person salary = easyRandom.nextObject(Person.class);
    
    // then
    assertThat(salary).isNotNull();
    assertThat(salary.name).isNull();
}
```
