### ISSUE TITLE
Inconsistent nanosecond precision between LocalTimeRangeRandomizer  and LocalDateTimeRangeRandomizer

### ISSUE THREAD

**Issue by Haixing-Hu** [j-easy/easy-random#414]
While the `LocalDateTimeRandomizer`, `LocalTimeRandomizer`, and `LocalTimeRangeRandomizer` generate date time values with the precision of seconds. Therefore the `LocalDateTimeRangeRandomizer` should also generate a `LocalDateTime` with the precision of seconds.

The following test cases will show the problem.

~~~

  @Test
  public void testEasyRandom() {
    EasyRandom random = new EasyRandom();
    final LocalDateTime datetime = random.nextObject(LocalDateTime.class);
    assertEquals(0, datetime.getNano());   // this will fail
  }

  @Test
  public void testLocalTimeRandomizer() {
    LocalDateTimeRandomizer randomizer = new LocalDateTimeRandomizer();
    final LocalDateTime datetime = randomizer.getRandomValue();
    assertEquals(0, datetime.getNano());   // this will pass
  }

  @Test
  public void testLocalTimeRangeRandomizer() {
    EasyRandomParameters parameters = new EasyRandomParameters();
    EasyRandomParameters.Range<LocalDate> dateRange = parameters.getDateRange();
    LocalDate minDate = dateRange.getMin();
    LocalDate maxDate = dateRange.getMax();
    EasyRandomParameters.Range<LocalTime> timeRange = parameters.getTimeRange();
    LocalTime minTime = timeRange.getMin();
    LocalTime maxTime = timeRange.getMax();
    LocalDateTimeRangeRandomizer randomizer = new LocalDateTimeRangeRandomizer(of(minDate, minTime), of(maxDate, maxTime));
    final LocalDateTime datetime = randomizer.getRandomValue();
    assertEquals(0, datetime.getNano());  // this will fail
  }

~~~

**Comment by benas** [comment]
Thank you for opening this issue. This is indeed inconsistent. However, instead of removing the nanosecond precision from `LocalDateTimeRangeRandomizer`, I would add this precision in `LocalTimeRandomizer` and `LocalTimeRangeRandomizer`.

I think it is better to make things more precise than less precise. Do you agree? If yes, please update #415 accordingly.

**Comment by benas** [comment]
This has been fixed by adding nano-second precision to `LocalTimeRandomizer` and `LocalTimeRangeRandomizer` instead of removing this precision from `LocalDateTimeRangeRandomizer`. Thank you for raising this inconsistency!
