### ISSUE TITLE
Random values for fields with more than one validation annotation

### ISSUE THREAD

**Issue by premanandc** [j-easy/easy-random#418]
Hello,

Thanks for building this really amazing random object generator library! It has saved me quite a lot lot of time!

When working with fields having more than one constraint annotation, like so:
```
    @NotBlank
    @Pattern(regexp = "^(EMP)?\\d{5}$", flags = CASE_INSENSITIVE)
    private String employeeId;
```
the `BeanValidationRandomizerRegistry` picks one of the annotation handlers for the field randomly, resulting in unpredictable behavior. For e.g. for the example above, one would expect that the `PatternAnnotationHandler` would always be used to generate values for the field, instead of the more generic `NotBlankAnnotationHandler`. However, because the `BeanValidationRandomizerRegistry` is backed by a `HashMap`, this is not deterministic - resulting in the wrong values being generated (sometimes). This is obviously undesirable.

This can be corrected using one of:

1. Assigning an explicit order for the annotations OR more simply
2. Using a more suitable collection (for instance a `LinkedHashMap` to hold the annotation handlers so as to ensure deterministic behavior when choosing a `Randomizer`

I understand there are workarounds for this. However, they become cumbersome pretty quickly. I am happy to provide a PR to help address this. Do let me know.

Thanks once again for making this wonderful library!

**Comment by benas** [comment]
Hi @premanandc ,

This is a known limitation documented [here](https://github.com/j-easy/easy-random/wiki/known-limitations#bean-validation). As mentioned in #285 and #351, there is no way to combine annotation handlers (imagine all combinations..). So this is left to the client side. You have a couple of options here:

* use a custom meta annotation (something like `@NonBlankPattern`) with a custom annotation handler (see example [here](https://github.com/j-easy/easy-random/blob/master/easy-random-bean-validation/src/test/java/org/jeasy/random/validation/MyCustomBeanValidationRandomizerRegistry.java)).
* create a custom randomizer and register it for fields defined with `FieldPredicates.isAnnotatedWith(NotBlank.class).and(FieldPredicates.isAnnotatedWith(Pattern.class))`

Thank you for opening this issue anyway! I'm glad you like the library!

**Comment by dadiyang** [comment]
I think, we can just ignore the NotNull/NotBlank/NotEmpty annotations. Handling these annotations are unnecessary for generating random value.
