### ISSUE TITLE
Choose a random value from a fixed list of values

### ISSUE THREAD

**Issue by mperezi** [j-easy/easy-random#431]
Sorry if this has been asked before but.. 

Is there any built-in randomizer that does what `ConstantRandomizer` does but extended to multiple values? Example:

```java
public ConstantListRandomizer(T... values) {
    this.values = values;
}
```

```java
@Override
public T getRandomValue() {
    return values[random.nextInt(values.length-1)];
}
```

One solution would be using a lambda expression:

```java
var parameters = new EasyRandomParameters()
        .randomize(FieldPredicates.named("countryIso"), () -> List.of("en", "es").get(new Random().nextInt(2)));
```

But that looks ugly, doesn't it?

**Comment by benas** [comment]
Yes, [GenericStringRandomizer](https://github.com/j-easy/easy-random/blob/master/easy-random-randomizers/src/main/java/org/jeasy/random/randomizers/GenericStringRandomizer.java) is what you are looking for. It allows you to generate a random value from a list of strings.
