### ISSUE TITLE
Map of Lists or Map of Map etc. is not being generated

### ISSUE THREAD

**Issue by aaramg** [j-easy/easy-random#454]
```
public class A {
        private Map<String, List<String>> map;
        private Map<String, Map<CsvHeaderEnum, String>> mapOfMap;
} 
```
```
@UtilityClass
public class Randomizer {

    private static final EasyRandom randomizer = new EasyRandom(
            new EasyRandomParameters()
                    .seed(123L)
                    .objectPoolSize(20)
                    .randomizationDepth(4)
                    .charset(StandardCharsets.UTF_8)
                    .stringLengthRange(5, 10)
                    .collectionSizeRange(1, 5)
                    .scanClasspathForConcreteTypes(true)
                    .overrideDefaultInitialization(true)
                    .ignoreRandomizationErrors(true)
    );

    public static EasyRandom randomizer() {
        return randomizer;
    }
}
```
This kind of nested Maps, Collections are not being generated.
It is very trivial to test, that is why I am not providing you step by step reproduction of the case.
Would be nice to have a recursively nested map, collection randomizer.

Thanks in advance.

**Comment by benas** [comment]
Thank you for opening this issue. This is a known limitation documented here: https://github.com/j-easy/easy-random/wiki/known-limitations#composite-collections. You can register custom randomizers for this kind of fields.

**Comment by aaramg** [comment]
Thanks for the fastest response. Then is there a way to generate a normal `Map<String, SomeClass> map` calling new `EasyRandom().smth`... I mean some workaround. Because the only method I see that is streaming is `EasyRandom().objects()`
