### ISSUE TITLE
Generate strings of length mentioned in JPA Constraints

### ISSUE THREAD

**Issue by kurasaiteja** [j-easy/easy-random#460]
Class A {
   @Column(
               name="number"
               length=5
   )
   getter....
  setter.....
}

Get Easy Random is ignoring the length constraint and generating random length strings. How to overcome this?

**Comment by fmbenhassine** [comment]
JPA support can be added as a separate extension similar to the Bean Validation module.

There is no plan to make ER depend on the Java Persistence API (for the same reason as in #499). If you are interested in developing and maintaining such a module, please let me know and I will add a reference to it in the [README](https://github.com/j-easy/easy-random#extensions). Thank you.
