### ISSUE TITLE
Initialized empty Collection is not populated

### ISSUE THREAD

**Issue by BenVercammen** [j-easy/easy-random#461]
In our project, we work with generated classes that contain List properties. 

At first this code was generated from WSDL's, and the List properties would not be initialized in the generated code. 
``protected List<SomeType> list;``

However, we are now generating the code from an OpenAPI spec and the List properties are already initialized.
``private List<SomeType> list = new ArrayList<>();``

This causes an issue as these lists are not populated because they are not null anymore.

I've already created a test and a fix, I'll open a pull request in a minute.

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. However, as mentioned by @msievers , you can use the `overrideDefaultInitialization`, which is designed specifically for that case. Here is the section in the docs that explains that parameter with an example: https://github.com/j-easy/easy-random/wiki/Randomization-parameters#override-default-initialization.

I am closing this issue and the corresponding PRs as I believe the solution is already implemented with the `overrideDefaultInitialization` parameter. Thank you for your time anyway.

@msievers Thank you for the follow up!
