### ISSUE TITLE
[Bug] kotlin value class as wrapper for uuid prodcues invalid uuid

### ISSUE THREAD

**Issue by theexiile1305** [j-easy/easy-random#465]
Hey,

thank you very much for this great project. 

Sometimes it is necessary for business logic to create a wrapper around some type. To solve such issues, Kotlin introduces a special kind of class called an [inline class](https://github.com/Kotlin/KEEP/blob/master/notes/value-classes.md). Inline classes are a subset of value-based classes. They don't have an identity and can only hold values.

Given this context I am using such a inline class to hold an UUID of an business object like `Todo`

```
data class Todo(
    val uuid: TodoID,
    val uuid2: UUID,
    val title: String,
    val description: String,
)
```

_EasyRandom_ now generates a correct UUID `uuid2` `40d7d115-92fa-2632-9bda-574542460f3a`,  if you are using the plain UUID object. However, if you are using the inline class `TodoID` _EasyRandom_ generates not a correct UUID `b921f1dd-3cbc-0495-fdab-8cd14d33f0aa`
```
@JvmInline
value class TodoID(private val value: UUID) {

    companion object {
        fun fromString(id: String): TodoID = TodoID(UUID.fromString(id))

        fun create() = TodoID(UUID.randomUUID())
    }

    override fun toString(): String = value.toString()
}
```

You can checkout a minimal example at the following GitHub-Repository --> [https://github.com/theexiile1305/easy-random-bug]( https://github.com/theexiile1305/easy-random-bug)

Many thanks upfront!

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. Do you mean ER is unable to generate a random instance of `TodoID`?

> EasyRandom now generates a correct UUID uuid2 40d7d115-92fa-2632-9bda-574542460f3a, if you are using the plain UUID object. However, if you are using the inline class TodoID EasyRandom generates not a correct UUID b921f1dd-3cbc-0495-fdab-8cd14d33f0aa

I am not a Kotlin expert, but how did you conclude that? What is incorrect about that UUID? I see it similar to the first one you mention it.

If the type is not a regular Java bean or record, you can create a custom randomizer for it.

**Comment by theexiile1305** [comment]
This ticket can be closed because it is no longer current. Thanks anyway!
