### ISSUE TITLE
EasyRandom generates the same values

### ISSUE THREAD

**Issue by mehhras** [j-easy/easy-random#470]
Hi guys, 

I have a question, and that is easy-random generates the similar values throughout my java spring boot tests. To do so, I create a class and I create a field in it:

```
public class MajorProvider {

    EasyRandom easyRandom;

    public MajorProvider() {
        EasyRandomParameters parameters = new EasyRandomParameters()
                .objectPoolSize(100)
                .randomizationDepth(3)
                .charset(StandardCharsets.UTF_8)
                .stringLengthRange(5, 50)
                .collectionSizeRange(1, 10)
                .scanClasspathForConcreteTypes(true)
                .overrideDefaultInitialization(false)
                .ignoreRandomizationErrors(true);
        parameters.excludeField(FieldPredicates.named("programInfoTypes"));
        easyRandom = new EasyRandom(parameters);

    }
}
```

Then, I have a function to generate my complex objects: ( MajorMetadataDto has only two strings )

```
   public MajorMetadataDto getOKMajorMetadataDto() {
        return easyRandom.nextObject(MajorMetadataDto.class);
    }

```

And I use this function like this:
```
@RepeatedTest(value = 3)
void should_failToUpdateMajorMetadata_when_NoSlug() {
...
      final MajorMetadataDto input = majorProvider.getOKMajorMetadataDto();
...
  }

```

And my problem is that `getOKMajorMetadataDto` , which calls easyrandom, generates the same values throughout all the tests. So, what should I do?

Thank you in advance.

**Comment by npepinpe** [comment]
In order for the randomized values to change, you need to reuse the same instance all the time, or change the seed between tests. What happens is that a new `EasyRandom` always uses the same starting seed, so you end up with the same values when you use a fresh instance every time. 

Be wary of making `EasyRandom` static though - it doesn't look thread safe, so it wouldn't play nice with concurrent tests. But if you run your tests in a single thread, then you could make a single static instance. Or if you're on Junit 5, you could set the lifecycle of your test to the class, i.e. `@TestInstance(LifeCycle.PER_CLASS)`, if that works for you. Same issues with concurrent tests however, so be careful.

Alternatively, you could also just change the seed between tests, but that would reduce the predictability of your tests when it comes to reproducing.

**Comment by fmbenhassine** [comment]
@mehhras The answer by @npepinpe is what you are looking for.

Thank you for the follow-up @npepinpe ! Much appreciated!
