### ISSUE TITLE
Dependency java-faker:1.0.2 is incompatible with actual Spring Boot 2.7.0

### ISSUE THREAD

**Issue by JeTam3** [j-easy/easy-random#477]
After upgrading Spring Boot version from 2.6.8 to 2.7.0 and using easy-random in my project. I failed into building problem.

I am getting error:
`Could not find snakeyaml-1.30-android.jar (org.yaml:snakeyaml:1.30).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.30/snakeyaml-1.30-android.jar`
    
This happend because easy-random is using java-faker in version 1.0.2 which is  [incompatible with actual Spring Boot 2.7.0 version](https://github.com/DiUS/java-faker/issues/733)

**Comment by dvgaba** [comment]
Below might help, java-faker is replaced with data-faker

https://repo1.maven.org/maven2/io/github/dvgaba/easy-random-core-jdk11/6.1.1/

https://repo1.maven.org/maven2/io/github/dvgaba/easy-random-core/6.1.1/

**Comment by vadim-levotsky** [comment]
Created a PR for replacing dependency 
https://github.com/j-easy/easy-random/pull/490

**Comment by fmbenhassine** [comment]
Fixed in #490. Thank you @vadim-levotsky!
