### ISSUE TITLE
BigDecimalRangeRandomizer does not generate values with configured scale

### ISSUE THREAD

**Issue by RedeemerSK** [j-easy/easy-random#480]
https://github.com/j-easy/easy-random/blob/0426dcd8b2df555d276a16513ab92d79f99f8de5/easy-random-core/src/main/java/org/jeasy/random/randomizers/range/BigDecimalRangeRandomizer.java#L84

Argument `scale` is incorrectly passed to `DoubleRangeRandomizer` as `seed` parameter.

**Comment by fmbenhassine** [comment]
Resolved in #486
