### ISSUE TITLE
Make release to maven local or jitpack

### ISSUE THREAD

**Issue by iirekm** [j-easy/easy-random#498]
Last release of EasyRandom is from 2020, it doesn't support e.g. jakarta-validation (only old javax.validation).

I tried to get EasyRandom from JitPack - unfortunately it fails: https://jitpack.io/com/github/j-easy/easy-random/5c430b4c8f/build.log

Release is needed. For example recent versions of Spring Boot use jakarta-validation, so we can't use EasyRandom now, although it helped for years in old versions.

**Comment by fmbenhassine** [comment]
I am going to release ER v6 to maven central. However, it won't contain the bean validation module anymore, see #499.
