### ISSUE TITLE
Fields with optional values

### ISSUE THREAD

**Issue by eric-taix** [j-easy/easy-random#5]
It will be very useful to have optional value for a field. In most real applications some fields are not set (ie if the mail is not required then some users will leave it blank). For testing purpose it's always a good thing to reflect the real world.

This can be solved by saying that if a Randomizer returns null then it means it does not want to set the field. Then it's easy to add an OptionalRandomizer (with a percent) which according to that percent returns null or a random value returned by a delegate.

**Comment by Toilal** [comment]
While working on #32 , I have an issue with this behavior. I have a randomizer than MUST return null, and then the null value must be set on the bean. It is for validation @Null implementation.

I think the best solution is to throw an exception when the user really need to skip this value generation (I suggest `DefaultValueException` for the name).
