### ISSUE TITLE
mvn repo does not have respective jar file

### ISSUE THREAD

**Issue by nagkumar** [j-easy/easy-random#510]
<img width="541" alt="image" src="https://github.com/j-easy/easy-random/assets/332234/49a68bca-8df7-4cd6-b410-a80111e68b19">

https://repo1.maven.org/maven2/org/jeasy/easy-random/5.0.0/

**Comment by nagkumar** [comment]
May be because of this my IDE is complaining

<img width="673" alt="image" src="https://github.com/j-easy/easy-random/assets/332234/38d76e3c-4edb-440a-a1b2-40f21b00a6de">

Can any confirm where to download the respective jar file through gradle

**Comment by nagkumar** [comment]
Anybody to help..

should I use it as this dependency

_```
// https://mvnrepository.com/artifact/org.jeasy/easy-random-core
testImplementation("org.jeasy:easy-random-core:5.0.0")
```_

rather than as

_`"org.jeasy:easy-random:5.0.0"`_

**Comment by fmbenhassine** [comment]
Yes, `easy-random-core` is the one you should use, as mentioned in the wiki: https://github.com/j-easy/easy-random/wiki/Getting-Started#maven-usage.
